spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pravat01
    username: postgres
    password: kumar
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9090